### ISSUE TITLE
Sapling/Overwinter Support - transaction.js

### ISSUE THREAD

**Issue by CryptoForge** [s-nomp/node-stratum-pool#25]
There is a issue with your recent sapling upgrade in the transaction.js file. This little snippet of code will cause the pool to not create over winter transactions correctly when sapling has been added to the coin options. What happens is that the first if statement for sapling returns true, but if the sapling block height has not been reached the second statement will return false and the overwinter statement will be skipped.

    if (coin.sapling) {
        if (coin.sapling === true || (typeof coin.sapling === 'number' && coin.sapling <= blockHeight)) {
            txb.setVersion(bitcoin.Transaction.ZCASH_SAPLING_VERSION);
        }
    } else if (coin.overwinter) {
        if (coin.overwinter === true || (typeof coin.overwinter === 'number' && coin.overwinter <= blockHeight)) {
            txb.setVersion(bitcoin.Transaction.ZCASH_OVERWINTER_VERSION);
        }
    }

I suggest you change the code to this.

        if (coin.sapling === true || (typeof coin.sapling === 'number' && coin.sapling <= blockHeight)) {
            txb.setVersion(bitcoin.Transaction.ZCASH_SAPLING_VERSION);
        }

        else if (coin.overwinter === true || (typeof coin.overwinter === 'number' && coin.overwinter <= blockHeight)) {
            txb.setVersion(bitcoin.Transaction.ZCASH_OVERWINTER_VERSION);
        }
    

Also you might want to change sapling and overwinter to saplingActivationHeight and overwinterActivationHeight for better descriptions.

**Comment by egyptianbman** [comment]
Good call, I'll push up a PR to remove the outer if statement.
