### ISSUE TITLE
Empty address in rewardRecipients will still deduct fee from coinbase

### ISSUE THREAD

**Issue by zzzpotato** [s-nomp/node-stratum-pool#49]
Currently the default `rewardRecipient` is empty with a 0.2 value. If the user does not specify an address here, the fee is deducted from the coinbase and given to no one as seen [here](https://insight.zeroclassic.org/block/0000496fb2314d032ab8dcfa8f0ccfbbc40ff17126b8a48f9b48a22dc4e357e4)

```
    "rewardRecipients": {
        "": 0.2
    },
```

https://github.com/s-nomp/node-stratum-pool/blob/0f3c9f894283935a213f5f9231681f58ad602ec1/lib/pool.js#L277-L296

I feel like most pool ops will always set this fee, however solo miners using s-nomp may not (thinking they are getting 100% anyways). Should we add a check here to let the pool operator know it's still blank? Maybe something simple like this?

```
        if('' in options.rewardRecipients) {
            emitErrorLog('No fee address specified!');
        }
```

Or perhaps we should set it to always use a value of 0 if no address is given?

**Comment by egyptianbman** [comment]
I'm good with whatever you like:
- Leave it as it is. This isn't intended to be "quick for anyone" software. Those running this should become familiar with at the very least, the configuration.
- Add `abcdefg` as the default address. Chains should reject blocks with an invalid wallet address.
- Set default rewardRecipients[0] to 0.
- Add a check that logs an error.

Any of those options works for me. :)

**Comment by zzzpotato** [comment]
Consider it a coin burn.
