### ISSUE TITLE
Error, founders reward missing for block template!

### ISSUE THREAD

**Issue by Serpent6877** [s-nomp/node-stratum-pool#57]
OS: Ubuntu 18.04
Block Daemon: zcashd 4.2.0

zcash.conf:
```
addnode=mainnet.z.cash
rpcuser=<my rpc user>
rpcpassword=<my password>
rpcthreads=8
rpcworkqueue=512
blocknotify=/pools/zecpool/blocknotify 127.0.0.1:17117 zec %s
```

Using latest S-NOMP from github. 

config.json:
```
  "defaultPoolConfigs": {
        "blockRefreshInterval": 0,
        "jobRebroadcastTimeout": 55,
        "connectionTimeout": 600,
        "emitInvalidBlockHashes": false,
        "validateWorkerUsername": true,
        "tcpProxyProtocol": false,



    "blockNotifyListener": {
    "enabled": true,
    "port": 17117
    }
```

Using the coins/zec.json that is in the git.

Continuously get the error of:
```
Error, founders reward missing for block template!
``` 

tcpdump of json packet from getblocksubsidy:
```
{"method":"getblocksubsidy","params":[1124772],"id":1611613376034}HTTP/1.1 200 OK
Content-Type: application/json
Date: Mon, 25 Jan 2021 22:22:56 GMT
Content-Length: 607
Connection: close

{"result":{"fundingstreams":[{"recipient":"Electric Coin Company","specification":"https://zips.z.cash/zip-0214","value":0.21875000,"valueZat":21875000,"address":"t3ZBdBe4iokmsjdhMuwkxEdqMCFN16YxKe6"},{"recipient":"Zcash Foundation","specification":"https://zips.z.cash/zip-0214","value":0.15625000,"valueZat":15625000,"address":"t3dvVE3SQEi7kqNzwrfNePxZ1d4hUyztBA1"},{"recipient":"Major Grants","specification":"https://zips.z.cash/zip-0214","value":0.25000000,"valueZat":25000000,"address":"t3XyYW8yBFRuMnfvm5KLGFbEVz25kckZXym"}],"miner":2.50000000,"founders":0.00000000},"error":null,"id":1611613376034}
```

Tried several different things but can't figure it out.

**Comment by zzzpotato** [comment]
See #56 and [this](https://github.com/s-nomp/s-nomp/pull/170)

It needs testing but worked on testnet

**Comment by Serpent6877** [comment]
Thanks! That seems to have fixed it for me so far!

**Comment by zzzpotato** [comment]
> Thanks! That seems to have fixed it for me so far!

If you can confirm you've found valid blocks on mainnet, we may be able to push these changes. Can you provide some valid block hashes or numbers if it has?

**Comment by Serpent6877** [comment]
I have found seven blocks on mainnet with these changes. Looks good there. However payouts look to take many hours to execute. With a single block found in a day. What is the rough time frame for payout after confirms?

**Comment by zzzpotato** [comment]
> I have found seven blocks on mainnet with these changes. Looks good there. However payouts look to take many hours to execute. With a single block found in a day. What is the rough time frame for payout after confirms?

Try sending a small amount of zec to your payout address to cover tx fee's and see if it speeds up.

**Comment by Serpent6877** [comment]
Ya tried that. Also set the payment time to 1800 and it still seems to run every minute.

```
2021-02-15 16:34:47 [Payments]	[zcash] Shielding operation success opid-b936c8d1-c9cf-491b-a830-eb466e07b573  txid: 1a303b4c80a7dee9cb87f5d012aaca78abe029315658cd489d4df95bb690b9a0
2021-02-15 16:35:04 [Payments]	[zcash] shieldcoinbase is waiting, too many operations already in progress.
2021-02-15 16:35:44 [Payments]	[zcash] Shielding operation success opid-b936c8d1-c9cf-491b-a830-eb466e07b573  txid: 1a303b4c80a7dee9cb87f5d012aaca78abe029315658cd489d4df95bb690b9a0
2021-02-15 16:36:41 [Payments]	[zcash] Shielding operation success opid-b936c8d1-c9cf-491b-a830-eb466e07b573  txid: 1a303b4c80a7dee9cb87f5d012aaca78abe029315658cd489d4df95bb690b9a0
2021-02-15 16:37:04 [Payments]	[zcash] sendZToT is waiting, too many z_sendmany operations already in progress.
2021-02-15 16:37:38 [Payments]	[zcash] Shielding operation success opid-b936c8d1-c9cf-491b-a830-eb466e07b573  txid: 1a303b4c80a7dee9cb87f5d012aaca78abe029315658cd489d4df95bb690b9a0
2021-02-15 16:38:35 [Payments]	[zcash] Shielding operation success opid-b936c8d1-c9cf-491b-a830-eb466e07b573  txid: 1a303b4c80a7dee9cb87f5d012aaca78abe029315658cd489d4df95bb690b9a0
2021-02-15 16:39:04 [Payments]	[zcash] shieldcoinbase is waiting, too many operations already in progress
2021-02-15 16:39:32 [Payments]	[zcash] Shielding operation success opid-b936c8d1-c9cf-491b-a830-eb466e07b573  txid: 1a303b4c80a7dee9cb87f5d012aaca78abe029315658cd489d4df95bb690b9a0
2021-02-15 16:41:04 [Payments]	[zcash] sendZToT is waiting, too many z_sendmany operations already in progress.
```

    "paymentProcessing": {
        "enabled": true,
        "minConf": 10,
        "paymentMode": "pplnt",
        "_comment_paymentMode": "prop, pplnt",
        "paymentInterval": 1800,
        "minimumPayment": 0.05,
        "maxBlocksPerPayment": 1,
        "daemon": {
            "host": "127.0.0.1",
            "port": 8232,
            "user": "zcashrpc",
            "password": "d1g1rPcP@ss!"
        }
    },


Payments seem to get stuck until I restart the Zcash daemon. I am running 4.2.0 from the repository. 

```
zecpool@poolw1:~$ zcash-cli z_getoperationstatus
[
  {
    "id": "opid-b936c8d1-c9cf-491b-a830-eb466e07b573",
    "status": "success",
    "creation_time": 1613295294,
    "result": {
      "txid": "1a303b4c80a7dee9cb87f5d012aaca78abe029315658cd489d4df95bb690b9a0"
    },
    "execution_secs": 0.440013,
    "method": "z_shieldcoinbase",
    "params": {
      "fromaddress": "t1dGomv6vidf7ychtujsxWChS5PpXKDzbfa",
      "toaddress": "zs107kzayee0vqkcndem6jj5zhu4kglxg27nkssa308km6zkcr39pn9wxl9p0nk30jl7t79cfjr0a7",
      "fee": 0.00001000
    }
  }
]
```

It seems that the operation status sits for an extended period of time. I can run z_getoperationstatus for hours and still see the z_shieldcoinbase operation success. But I don't see a z_sendmany operation but still get the above error.

**Comment by zzzpotato** [comment]
Ah, this is a known bug. Try this

Above this line https://github.com/zzzpotato/s-nomp/blob/86610aa518a40e58a962158cad0cfb2a069e22a9/libs/paymentProcessor.js#L494

Add the following:

```
                /* Clear stuck operations*/
                logger.special(logSystem, logComponent, "Running z_operationresult to clear finished operations");
                batchRPC.push(['z_getoperationresult']);
```

This should auto clear the the stuck operations. Let me know how it goes.

**Comment by Serpent6877** [comment]
Thanks that appears to have done the trick!
